typography_spectrum: 0.9557082871906459
color:
  saturation: 0.8749100905843079
  brandStrength: 0.5085254244040698
  rhythmicContrast: 0.8132449549157172
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  lightness: 0.7776441683527082
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
name: Karcher
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: SONY
    id: eb210b20-ae59-4775-9667-88ff5eeed371
    type: content
  - name: 'Illumina '
    id: 37b38244-228f-42ef-81fb-c966bacd8a99
    type: content
  - name: WestLiving
    id: 57060fa2-a5a4-42e0-b8ac-75be465d93a7
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
