layout_spectrum: 0
typography_spectrum: 0.9557082871906459
color:
  saturation: 0.8749100905843079
  brandStrength: 0.5085254244040698
  rhythmicContrast: 0.8132449549157172
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  lightness: 0.7776441683527082
favicon: null
name: Karcher
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
